apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 5s
  ref:
    branch: main
  url: https://github.com/meysam81/test-fluxcd-orphan-parent-gitops
